### ISSUE TITLE
The cayman theme is not currently supported on GitHub Pages

### ISSUE THREAD

**Issue by DSoko2** [pages-themes/cayman#130]
I get the following error since July 22nd 2021 when building Github Pages with the cayman theme, if the following two lines are included in the _config:

```
github:
  is_project_page: false
```

Removing these from the _config solves the issue in my case. However, I would like to have that configuration to hide the "View on GitHub" button.

The build error:

```
The page build failed for the `main` branch with the following error:

The cayman theme is not currently supported on GitHub Pages. For more information, see https://docs.github.com/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll.
```

Repo I investigated and faced this issue on: https://github.com/DSoko2/Corona-NI

**Comment by retroluxfilm** [comment]
I get the same error on my page with my github pages. Just changed some page contents and ran into that issue. Might be connected that the CI fails due to  404 on <link rel="preconnect" href="https://fonts.gstatic.com"> ?

**Comment by squallstar** [comment]
I'm getting a similar problem since a few hours ago:

![image](https://user-images.githubusercontent.com/574210/126789438-1b4e053b-f27a-4820-aecc-01c7c108793a.png)

**Comment by parkr** [comment]
> Removing these from the _config solves the issue in my case

This is very, very strange. I can confirm that a basic `_config.yml` works fine, but adding `github.is_project_page: false` seems to break the build. 🤔

**Comment by parkr** [comment]
@squallstar Interesting – the Sass in this repo is `jekyll-theme-cayman.scss` (https://github.com/pages-themes/cayman/blob/master/_sass/jekyll-theme-cayman.scss). Not sure how importing `cayman` would have worked before? 🤔

**Comment by dangowans** [comment]
> I'm getting a similar problem since a few hours ago:
> 
> ![image](https://user-images.githubusercontent.com/574210/126789438-1b4e053b-f27a-4820-aecc-01c7c108793a.png)

Getting the same issue as @squallstar after adding `assets/css/style.scss`.  I removed it and things worked again.

**Comment by dangowans** [comment]
It looks like this issue is affecting more than just cayman.

https://github.community/t/the-primer-theme-is-not-currently-supported-on-github-pages/191770

**Comment by AnonyPla** [comment]
It's also affecting the hacker theme 

https://github.com/pages-themes/hacker/issues/77 

https://github.community/t/the-hacker-theme-is-not-currently-supported-on-github-pages/191708

**Comment by parkr** [comment]
Hey folks, please try again now and let me know how it's working for you. If things are still broken, please let me know how!

**Comment by DSoko2** [comment]
Works again for me. At least my issue described in the original post of this issue is fixed. Thank you!

**Comment by AnonyPla** [comment]
Small comment ... I still have the "issue" when trying to build locally with bundle ...

**Comment by AnonyPla** [comment]
Does it work locally for you guys? Because for me it works online but it's still broken when trying the build/serve the site using bundle.

**Comment by Jmuccigr** [comment]
Another report of a similar problem [here](https://github.community/t/jekyll-theme-minimal-not-working/191791). Still not working.

**Comment by pox** [comment]
Not sure it's the same issue @Jmuccigr .
The error I'm getting with hacker theme is:

```
Your SCSS file assets/css/style.scss has an error on line 1: File to import not found or unreadable: hacker. Load path: /tmp/jekyll-remote-theme-20210724-6-10nliyy/_sass.
```

But in any case the error seems to be unrelated to a specific theme - it's a general github pages issue I suspect.

**Comment by filipvanlaenen** [comment]
I got things working again by removing `assets/css/style.scss`, but as soon as I add the file again to make a custom change, it's broken. The problem is that it breaks on the import, whether you import just `""` or `"{{ site.theme }}"`.

**Comment by pox** [comment]
That basically means no customization possible and a zillion pages currently broken

**Comment by filipvanlaenen** [comment]
I think so, @pox . Is there a separate ticket for that issue?

**Comment by filipvanlaenen** [comment]
I've described the problem here: https://github.community/t/github-pages-breaks-upon-adding-assets-css-style-scss/191906

**Comment by AnonyPla** [comment]
My issues were the same but with a different theme (hacker) got solved "online" with the fix above. My issue when building locally with bundle got solved by changing this in the scss style files:

`@import "{{ site.theme }}";`

to 

`@import 'jekyll-theme-hacker';` (in my case if was the hacker theme)

And by adding `gemspec` to the gemfile (locally) as well as using the one provider by the theme. In this case it would be https://github.com/pages-themes/cayman/blob/master/jekyll-theme-cayman.gemspec.

I also added the gemspec file to the .gitignore

Also I had to install the actual theme gem so `gem install jekyll-theme-hacker` which was not needed before. This solved all my issues locally and online.

**Comment by pox** [comment]
@AnonyPla's fix (https://github.com/pages-themes/cayman/issues/130#issuecomment-886056882) works for me as well.

**Comment by Jmuccigr** [comment]
> @AnonyPla's fix ([#130 (comment)](https://github.com/pages-themes/cayman/issues/130#issuecomment-886056882)) works for me as well.

Yes, this works for me too (_mutatis mutandis_ since I use the minimal theme which I already have installed locally), but it's more a work-around than a fix, no? The theme should be import-able from the config file without hardcoding it into the scss.

**Comment by DaveSkender** [comment]
I've expanded on this fix from @AnonyPla [here](https://github.com/pages-themes/cayman/issues/131#issuecomment-886092689).  Basically, I'd also recommend an explicit add of the theme to your `GemFile`.

**Comment by AnonyPla** [comment]
Yes and I edited my solution based on yours. The gemspec file is not needed. But in my case I had to install the theme using gem too. It wasn't there.

**Comment by Jas0n0ss** [comment]
You should change *`theme`*  from `cayman` to `jekyll-theme-cayman` in your `_config.yaml`
